### ISSUE TITLE
Conversion of URLs to links on seminar pages

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#165] opened 2020-04-20 01:25 UTC
It seems that sometimes on a seminar's page, a URL in the description gets mangled with the next word before being converted to a link.

For an example, see

https://master.mathseminars.org/seminar/mitpde

**Comment by AndrewVSutherland** [comment] 2020-04-20 01:30
I know where the problem is.

**Comment by AndrewVSutherland** [comment] 2020-04-20 02:35
This is now fixed on master, see https://master.mathseminars.org/seminar/mitpde.

**Closed by AndrewVSutherland** 2020-04-20 02:35 UTC
Labels: bug
